[2024-07-30 11:59:37,301: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-30 11:59:37,303: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-30 12:00:51,233: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-30 12:00:51,234: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-30 14:17:34,747: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-30 14:17:34,749: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-30 14:17:59,943: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-30 14:17:59,946: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-30 14:20:53,959: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-30 14:20:53,961: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-30 14:22:18,299: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-30 14:22:18,302: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-30 14:36:17,362: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-07-30 14:36:17,369: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-30 14:36:17,370: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-30 14:36:17,370: ERROR: main: yaml file is empty]
Traceback (most recent call last):
  File "C:\projects\OncoFlow-Deep-Learning-MLOps-for-Adenocarcinoma\src\cnnClassifier\utils\common.py", line 33, in read_yaml
    return ConfigBox(content)
           ^^^^^^^^^^^^^^^^^^
  File "C:\projects\OncoFlow-Deep-Learning-MLOps-for-Adenocarcinoma\venv\Lib\site-packages\box\box.py", line 259, in __init__
    raise BoxValueError("First argument must be mapping or iterable")
box.exceptions.BoxValueError: First argument must be mapping or iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\projects\OncoFlow-Deep-Learning-MLOps-for-Adenocarcinoma\main.py", line 12, in <module>
    obj.main()
  File "C:\projects\OncoFlow-Deep-Learning-MLOps-for-Adenocarcinoma\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 14, in main
    config = ConfigurationManager()
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\projects\OncoFlow-Deep-Learning-MLOps-for-Adenocarcinoma\src\cnnClassifier\config\configuration.py", line 16, in __init__
    self.params = read_yaml(params_filepath)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\projects\OncoFlow-Deep-Learning-MLOps-for-Adenocarcinoma\venv\Lib\site-packages\ensure\main.py", line 872, in __call__
    return_val = self.f(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\projects\OncoFlow-Deep-Learning-MLOps-for-Adenocarcinoma\src\cnnClassifier\utils\common.py", line 35, in read_yaml
    raise ValueError("yaml file is empty")
ValueError: yaml file is empty
[2024-07-30 14:40:56,088: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-07-30 14:40:56,088: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-30 14:40:56,089: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-30 14:40:56,089: ERROR: main: yaml file is empty]
Traceback (most recent call last):
  File "C:\projects\OncoFlow-Deep-Learning-MLOps-for-Adenocarcinoma\src\cnnClassifier\utils\common.py", line 33, in read_yaml
    return ConfigBox(content)
           ^^^^^^^^^^^^^^^^^^
  File "C:\projects\OncoFlow-Deep-Learning-MLOps-for-Adenocarcinoma\venv\Lib\site-packages\box\box.py", line 259, in __init__
    raise BoxValueError("First argument must be mapping or iterable")
box.exceptions.BoxValueError: First argument must be mapping or iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\projects\OncoFlow-Deep-Learning-MLOps-for-Adenocarcinoma\main.py", line 12, in <module>
    obj.main()
  File "C:\projects\OncoFlow-Deep-Learning-MLOps-for-Adenocarcinoma\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 14, in main
    config = ConfigurationManager()
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\projects\OncoFlow-Deep-Learning-MLOps-for-Adenocarcinoma\src\cnnClassifier\config\configuration.py", line 16, in __init__
    self.params = read_yaml(params_filepath)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\projects\OncoFlow-Deep-Learning-MLOps-for-Adenocarcinoma\venv\Lib\site-packages\ensure\main.py", line 872, in __call__
    return_val = self.f(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\projects\OncoFlow-Deep-Learning-MLOps-for-Adenocarcinoma\src\cnnClassifier\utils\common.py", line 35, in read_yaml
    raise ValueError("yaml file is empty")
ValueError: yaml file is empty
[2024-07-30 15:26:26,052: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-07-30 15:26:26,053: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-30 15:26:26,054: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-30 15:26:26,055: ERROR: main: yaml file is empty]
Traceback (most recent call last):
  File "C:\projects\OncoFlow-Deep-Learning-MLOps-for-Adenocarcinoma\src\cnnClassifier\utils\common.py", line 33, in read_yaml
    return ConfigBox(content)
           ^^^^^^^^^^^^^^^^^^
  File "C:\projects\OncoFlow-Deep-Learning-MLOps-for-Adenocarcinoma\venv\Lib\site-packages\box\box.py", line 259, in __init__
    raise BoxValueError("First argument must be mapping or iterable")
box.exceptions.BoxValueError: First argument must be mapping or iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\projects\OncoFlow-Deep-Learning-MLOps-for-Adenocarcinoma\main.py", line 12, in <module>
    obj.main()
  File "C:\projects\OncoFlow-Deep-Learning-MLOps-for-Adenocarcinoma\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 14, in main
    config = ConfigurationManager()
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\projects\OncoFlow-Deep-Learning-MLOps-for-Adenocarcinoma\src\cnnClassifier\config\configuration.py", line 16, in __init__
    self.params = read_yaml(params_filepath)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\projects\OncoFlow-Deep-Learning-MLOps-for-Adenocarcinoma\venv\Lib\site-packages\ensure\main.py", line 872, in __call__
    return_val = self.f(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\projects\OncoFlow-Deep-Learning-MLOps-for-Adenocarcinoma\src\cnnClassifier\utils\common.py", line 35, in read_yaml
    raise ValueError("yaml file is empty")
ValueError: yaml file is empty
[2024-07-30 15:29:46,148: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-07-30 15:29:46,149: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-30 15:29:46,152: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-30 15:29:46,152: INFO: common: created directory at: artifacts]
[2024-07-30 15:29:46,152: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-30 15:29:46,152: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1z0mreUtRmR-P-magILsDR3T7M6IkGXtY/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-07-30 15:30:41,910: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1z0mreUtRmR-P-magILsDR3T7M6IkGXtY/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-07-30 15:30:42,499: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-07-31 10:49:39,054: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-31 10:49:39,081: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-31 10:49:39,085: INFO: common: created directory at: artifacts]
[2024-07-31 10:50:24,330: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-31 10:50:24,334: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-31 10:50:24,336: INFO: common: created directory at: artifacts]
[2024-07-31 11:00:28,173: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-31 11:00:28,176: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-31 11:00:28,177: INFO: common: created directory at: artifacts]
[2024-07-31 11:30:54,312: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-31 11:30:54,326: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-31 11:30:54,328: INFO: common: created directory at: artifacts]
[2024-07-31 11:30:54,330: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-07-31 11:42:49,571: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-07-31 11:42:50,177: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-07-31 12:06:54,140: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-07-31 12:06:54,142: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-31 12:06:54,144: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-31 12:06:54,145: INFO: common: created directory at: artifacts]
[2024-07-31 12:06:54,145: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-31 12:06:54,146: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1z0mreUtRmR-P-magILsDR3T7M6IkGXtY/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-07-31 12:07:57,013: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1z0mreUtRmR-P-magILsDR3T7M6IkGXtY/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-07-31 12:07:57,619: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-07-31 12:07:57,620: INFO: main: *******************]
[2024-07-31 12:07:57,620: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-07-31 12:07:57,621: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-31 12:07:57,623: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-31 12:07:57,623: INFO: common: created directory at: artifacts]
[2024-07-31 12:07:57,624: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-07-31 12:07:58,196: ERROR: main: 'PrepareBaseModel' object has no attribute 'save_model']
Traceback (most recent call last):
  File "C:\projects\OncoFlow-Deep-Learning-MLOps-for-Adenocarcinoma\main.py", line 23, in <module>
    prepare_base_model.main()
  File "C:\projects\OncoFlow-Deep-Learning-MLOps-for-Adenocarcinoma\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 18, in main
    prepare_base_model.get_base_model()
  File "C:\projects\OncoFlow-Deep-Learning-MLOps-for-Adenocarcinoma\src\cnnClassifier\components\prepare_base_model.py", line 20, in get_base_model
    self.save_model(path=self.config.base_model_path, model=self.model)
    ^^^^^^^^^^^^^^^
AttributeError: 'PrepareBaseModel' object has no attribute 'save_model'
[2024-07-31 14:04:44,195: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-31 14:04:44,208: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-31 14:04:44,213: INFO: common: created directory at: artifacts]
[2024-07-31 14:04:44,218: INFO: common: created directory at: artifacts\training]
[2024-07-31 14:04:45,335: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-07-31 14:06:17,768: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-31 14:06:17,772: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-31 14:06:17,774: INFO: common: created directory at: artifacts]
[2024-07-31 14:06:17,775: INFO: common: created directory at: artifacts\training]
[2024-07-31 14:06:18,008: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-07-31 14:07:41,377: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-31 14:07:41,379: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-31 14:07:41,380: INFO: common: created directory at: artifacts]
[2024-07-31 14:07:41,381: INFO: common: created directory at: artifacts\training]
[2024-07-31 14:07:41,635: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-07-31 14:09:40,693: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-31 14:09:40,696: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-31 14:09:40,697: INFO: common: created directory at: artifacts]
[2024-07-31 14:09:40,699: INFO: common: created directory at: artifacts\training]
[2024-07-31 14:09:41,407: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-07-31 14:11:05,638: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-31 14:11:05,644: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-31 14:11:05,647: INFO: common: created directory at: artifacts]
[2024-07-31 14:11:05,650: INFO: common: created directory at: artifacts\training]
[2024-07-31 14:11:06,323: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-07-31 14:11:41,847: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-31 14:11:41,849: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-31 14:11:41,851: INFO: common: created directory at: artifacts]
[2024-07-31 14:11:41,853: INFO: common: created directory at: artifacts\training]
[2024-07-31 14:11:42,332: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-07-31 14:14:34,149: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-31 14:14:34,152: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-31 14:14:34,153: INFO: common: created directory at: artifacts]
[2024-07-31 14:14:34,154: INFO: common: created directory at: artifacts\training]
[2024-07-31 14:14:34,676: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-07-31 14:23:15,078: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-31 14:23:15,081: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-31 14:23:15,083: INFO: common: created directory at: artifacts]
[2024-07-31 14:23:15,084: INFO: common: created directory at: artifacts\training]
[2024-07-31 14:23:15,709: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-07-31 14:29:10,319: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-31 14:29:10,321: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-31 14:29:10,323: INFO: common: created directory at: artifacts]
[2024-07-31 14:29:10,324: INFO: common: created directory at: artifacts\training]
[2024-07-31 14:29:10,811: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-07-31 14:29:53,825: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-08-02 02:45:35,394: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-08-02 02:45:35,396: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-02 02:45:35,397: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-02 02:45:35,398: INFO: common: created directory at: artifacts]
[2024-08-02 02:45:35,399: INFO: common: created directory at: artifacts/data_ingestion]
[2024-08-02 02:45:35,399: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1z0mreUtRmR-P-magILsDR3T7M6IkGXtY/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-02 02:46:43,800: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1z0mreUtRmR-P-magILsDR3T7M6IkGXtY/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-02 02:46:44,489: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-08-02 02:46:44,490: INFO: main: *******************]
[2024-08-02 02:46:44,490: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-08-02 02:46:44,492: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-02 02:46:44,493: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-02 02:46:44,493: INFO: common: created directory at: artifacts]
[2024-08-02 02:46:44,493: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-08-02 02:46:45,159: ERROR: main: 'PrepareBaseModel' object has no attribute 'save_model']
Traceback (most recent call last):
  File "C:\projects\OncoFlow-Deep-Learning-MLOps-for-Adenocarcinoma\main.py", line 25, in <module>
    prepare_base_model.main()
  File "C:\projects\OncoFlow-Deep-Learning-MLOps-for-Adenocarcinoma\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 18, in main
    prepare_base_model.get_base_model()
  File "C:\projects\OncoFlow-Deep-Learning-MLOps-for-Adenocarcinoma\src\cnnClassifier\components\prepare_base_model.py", line 20, in get_base_model
    self.save_model(path=self.config.base_model_path, model=self.model)
    ^^^^^^^^^^^^^^^
AttributeError: 'PrepareBaseModel' object has no attribute 'save_model'
